### ISSUE TITLE
Support for import_map.json?

### ISSUE THREAD

**Issue by creativenull** [vim-denops/denops.vim#91]
Hey I've been using this to build my own plugin, and really enjoying it 😄 over at [https://github.com/creativenull/projectlocal-vim](https://github.com/creativenull/projectlocal-vim)

I've noticed that `import_map.json` don't work the way it would on a normal deno project (which is expected as this is for building plugins), I was wondering if there would be any support if it's possible to use an import map to simplify imports in denops, instead of directly importing from a url or from within a `dep/` directory?

**Comment by lambdalisue** [comment]
Hi. I'm really glad that you've chosen "denops.vim" as an ecosystem of your plugin 👍 

Well, unfortunately there is an issue for using `import_map.json` on `Worker` (https://github.com/denoland/deno/issues/6675).
While denops.vim runs each plugin on individual Worker threads, the above issue is critical. That's why we've not even considered supporting `import_map.json` yet.

**Comment by lambdalisue** [comment]
Note that denops.vim itself uses [`deps.ts`](https://deno.land/manual@v1.11.3/linking_to_external_code#it-seems-unwieldy-to-import-urls-everywhere) with [deno-udd][] to manage dependencies. At least for now, this is an official recommended way to manage dependencies on denops.vim plugins.

[deno-udd]: https://github.com/hayd/deno-udd

**Comment by creativenull** [comment]
Ah I see, completely glossed over the fact that its being run inside a separate worker thread and the linked issue makes sense.

I will look into using deno-udd for managing dependencies and close this issue for now, thanks for your reply!
